#!/bin/bash

clear 
echo '
---------------------------------------
 PACKAGE MAINTENANCE AND UPDATE
 devel null@2024   -  yuros.org
---------------------------------------
'

read -p "Hello Mr $USER, Do you want update your system right now ? ( Y/n ) " SCRORPIO_SYSTEM_UPDATE

if [[ $SCRORPIO_SYSTEM_UPDATE == "Y" || $SCRORPIO_SYSTEM_UPDATE == "y" ]];then
	dateprefix=$(date +"%H%S")
	sudo cp /etc/pacman.d/mirrorlist /etc/pacman.d/mirrorlist-$dateprefix &&
    	reflector --country 'Indonesia,Singapore,Malaysia' --ipv4 &&
    	yay &&
    	yes y | yay -Scc &&
    	rm -fr ~/.cache/*
fi

